# Generated by Django 5.2.4 on 2025-07-24 10:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro_app', '0002_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=13)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField(default='')),
                ('profile_pic', models.FileField(default='', upload_to='', verbose_name='upload_to=farmer_pic/')),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
