# Generated by Django 5.2.4 on 2025-07-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro_app', '0003_farmer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('product_category', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=50)),
                ('product_price', models.CharField(max_length=50)),
                ('product_pic', models.FileField(default='', upload_to='product_pic/')),
                ('product_status', models.CharField(default='available', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='farmer',
            name='profile_pic',
            field=models.FileField(default='', upload_to='farmer_pic/'),
        ),
    ]
