# Generated by Django 5.2.4 on 2025-08-02 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agro_app', '0004_product_alter_farmer_profile_pic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
