# Generated by Django 5.2.4 on 2025-08-02 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro_app', '0005_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=50)),
                ('product_price', models.CharField(max_length=50)),
                ('product_pic', models.FileField(default='', upload_to='product_pic/')),
                ('product_status', models.CharField(default='available', max_length=100)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='agro_app.farmer')),
            ],
        ),
    ]
