# Generated by Django 5.2.4 on 2025-08-18 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agro_app', '0006_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.RemoveField(
            model_name='product',
            name='farmer',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='Farmer',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
